# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180803_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='tag_org',
        ),
    ]
